version: '2'

services:
    application:
        image: pwsz-application
        build:
            context: .
            dockerfile: docker/application/Dockerfile
        ports:
            - 8080:80
        volumes:
            - .:/var/www
        links:
            - database
            - cache
    database:
        image: pwsz-database
        build:
            context: .
            dockerfile: docker/database/Dockerfile
        ports:
            - 13306:3306
        environment:
            MYSQL_DATABASE: pwsz
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
    cache:
        image: pwsz-cache
        build:
            context: .
            dockerfile: docker/cache/Dockerfile
        ports:
            - 16379:6379